# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'
services:
  bmo.test:
    build:
      context: ./docker/bmo
      dockerfile: ./Dockerfile
    volumes:
      - bmo-mysql-db:/var/lib/mysql
      - /home/dkl/devel:/home/bugzilla/devel
      - /home/dkl/.bz-dev.conf:/etc/bz-dev.conf:ro

  demo:
    build:
      context: docker/vct-hg
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/phab/repo:ro
    depends_on:
      - tinyproxy
      - phabricator.test
      - bmo.test

  phabricator:
    image: mozilla/phabext
    environment:
      - MYSQL_HOST=phabdb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - PHABRICATOR_URI=http://phabricator.test/
      - PHABRICATOR_CDN_URI=http://phabricator.test/
    restart: on-failure
    depends_on:
      - phabdb

  phabricator.test:
    image: nginx:alpine
    volumes:
      - ./docker/phabricator/site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - phabricator
    depends_on:
      - phabricator
      - tinyproxy

  phabdb:
    image: mysql:5.5
    volumes:
      - phabricator-mysql-db:/var/lib/mysql
      - ./docker/phabricator/mysql:/etc/mysql/conf.d:ro
      - ./docker/phabricator/demo.sql.gz:/docker-entrypoint-initdb.d/demo.sql.gz
    environment:
      - MYSQL_ROOT_PASSWORD=password

  tinyproxy:
    build:
      context: docker/tinyproxy
      dockerfile: ./Dockerfile
    ports:
      - "1080:1080"

volumes:
  bmo-mysql-db:
  phabricator-mysql-db:
